workspace/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  root 'brown#main'
  
  get ':controller(/:action(/:id))'
  post ':controller(/:action(/:id))'
  

end

workspace/app/models/campushash.rb
class Campushash < ActiveRecord::Base
    has_many :posthashrels
    has_many :userhashrels
    
    
    
end

workspace/app/models/post.rb
class Post < ActiveRecord::Base
    has_many :posthashrels
    has_many :postuserrels
    default_scope {order('post_deadline ASC')}

end

workspace/app/models/posthashrel.rb
class Posthashrel < ActiveRecord::Base
    belongs_to :post
    belongs_to :campushash
end

workspace/app/models/postuserrel.rb
class Postuserrel < ActiveRecord::Base
    belongs_to :post
    belongs_to :user
end

workspace/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]
  
  has_many :postuserrels
  has_many :userhashrels
  
  def self.from_omniauth(auth)
    check_presence = where(email: auth.info.email).take
    if where(email: auth.info.email).take.nil?
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
      end
    else
      update(check_presence.id, :provider => auth.provider, :uid => auth.uid)
    end
  end
  
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
  
end

workspace/app/models/userhashrel.rb
class Userhashrel < ActiveRecord::Base
    belongs_to :user
    belongs_to :campushash
end

workspace/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

workspace/app/controllers/brown_controller.rb
class BrownController < ApplicationController
  
  def main
    @bunny = "fat"
    @posts = Post.all
    
    if !current_user.nil?
      userhash = Userhashrel.where("user_id = ?", current_user.id)
      @usermango = []
      @usermelon = []
      
      userhash.each do |usershash|
        if usershash.pick_type == 0
          @usermango << usershash.campushash_id
        elsif usershash.pick_type == 1
          @usermelon << usershash.campushash_id
        end
     end
      
      mangolist = Postuserrel.order(mango: :desc).pluck(:post_id)
    
    end
    
  end
  
  def search 
  
  end
  
  def post_new     #p는 이름짓기 귀찮아서 선언한 변수명입니다 문제가 있으면 아무렇게나 바꿀 수 있습니다
    due_date = params[:deadline]
    input_hash = params[:hash].split(' ')
    p = Post.new
    p.post_image = params[:imageurl]
    p.post_category = params[:category]
    p.post_company = params[:company]
    p.post_subject = params[:subject]
    p.post_deadline = due_date["date"]
    p.post_content = params[:content]
    p.save
    
    input_hash.each do |hash|
      Campushash.find_or_create_by(hash_content: hash)
      
    end
    
    input_hash.each do |hash|
      post_hash_rel = Posthashrel.new
      post_hash_rel.post_id = p.id
      post_hash_rel.campushash_id = Campushash.find_by(hash_content: hash).id
      post_hash_rel.save
    end
    
    
    redirect_to '/brown/newpost'
    
    
  end

  def post_list
    @posts = Post.all
    
    if !params[:id].nil?    
    p = Post.find(params[:id])
    p.destroy
    redirect_to '/brown/post_list'
    end
          
  end
  
  def pickhash
    hashinput = params[:id].to_i
    postinput = params[:postid].to_i
    pick = Userhashrel.where("user_id= ? and campushash_id= ?", current_user.id, hashinput).take
    
    userpickmango = Userhashrel.where("user_id =? and pick_type =?", current_user.id, 0).pluck(:campushash_id)
    userpickmelon = Userhashrel.where("user_id=? and pick_type=?", current_user, 1).pluck(:campushash_id)
    
    #post의 우선순위를 위한 mango melon 점수 부여
      
    postpick = Postuserrel.where("post_id = ? and user_id = ?", postinput, current_user.id).take
    hashpost = Posthashrel.where("post_id=?", postinput).pluck(:campushash_id)
    postpick.mango = (userpickmango&hashpost).size
    postpick.melon = (userpickmelon&hashpost).size
    postpick.save
    
    if postpick.nil?
      postpick = Postuserrel.new
      postpick.user_id = current_user.id
      postpick.post_id = postinput
      postpick.save
      postpick = Postuserrel.where("post_id = ? and user_id = ?", postinput, current_user.id).take
    end
    
    
    
    if pick.nil?
    
      picked_hash = Userhashrel.new
      picked_hash.user_id = current_user.id
      picked_hash.campushash_id = hashinput
      picked_hash.pick_type = 0
      picked_hash.save
            
      elsif pick.pick_type == 0               #원래 망고인 것이 들어오면 1 더해줌
        pick.pick_type = pick.pick_type + 1
        pick.save
        
        
      else pick.pick_type  > 0                #원래 멜론이 들어오면 
          pick.destroy

    end
    
    redirect_to '/'
    
  end
  
  def user_hash 
    if !current_user.nil?
      userhash = Userhashrel.where("user_id = ?", current_user.id)
      @usermango = []
      @usermelon = []
      userhash.each do |usershash|
        if usershash.pick_type == 0
          @usermango << usershash.campushash_id
        elsif usershash.pick_type == 1
          @usermelon << usershash.campushash_id
        end
      end  
    end
  
  
  end
  
  
  
  
end

workspace/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

workspace/app/helpers/application_helper.rb
module ApplicationHelper
end

workspace/app/helpers/brown_helper.rb
module BrownHelper
end

workspace/app/views/brown/_body_carousel.erb
<!--광고판-->
<div class="container-fluid" id="introduction">  
    <div class="row" style="padding-top:20px;margin-left: -;margin-left: 0px;margin-right: 0px;">  
        <div id="advertise" class="col-sm-8" style="padding-left:0px; padding-right:0px; height:100%">    
            <section class="no-padding" >
                <div id="carousel" class="carousel slide no-padding" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carousel" data-slide-to="0" class="active"></li>
                        <li data-target="#carousel" data-slide-to="1" class=""></li>
                        <li data-target="#carousel" data-slide-to="2" class=""></li>
                    </ol>
        
                    <!-- Wrapper for slides -->
                    <div class="carousel-inner" role="listbox" >
                        <div class="item active">
                            <img class="carousel-img" src="assets/bg.png" >    
                            <div class="carousel-caption" style="text-align:center;">
                                <h2 class="section-heading font-green" style="font-family:impact;">공모전, 인턴, 대외활동, 취준정보</h2>
                                <br>
                                <div class="green" style="border: 3px solid rgb(255,204,41); width:30vw; border-radius:10px; font-size:20px;">
                                    <spans class="font-white">관심 <span class="font-yellow" style="font-weight:700" >해시태그</span> 설정하고</spans> 
                                </div>
                                <br>
                                    <a class="btn same-row yellow page-scroll" href="#whole-contents" style=" height:32px; padding-top:2px; padding-bottom:2px">
                                        <span style="color:black; font-size:18px; font-weight:700;">모아보고 + 알림받기 </span></a>
                                <br><br>
                            </div>
                        </div>
                        <div class="item">
                            <img src="assets/bg.png" class="carousel-size">
                            <div class="carousel-caption">
                                <h2 class="section-heading">화이팅 제몽소!</h2>
                                <hr class="light">
                                <h4>- 힘내서 만듭시다 으쌰으쌰</h4>
                                <h4>- 화이팅 개발자들    </h4>
                                <h4>- 화이팅 마케팅팀 </h4> 
                            </div>
                        </div>
                        <div class="item">
                            <img src="assets/bg.png" class="carousel-size">
                            <div class="carousel-caption">
                                <h2 class="section-heading">화이팅 캠컴</h2>
                                <hr class="light">
                                <h4>- 오픈 베타까지 6일!</h4>
                                <h4>- 김민규 최인영 김권영 노대원 화이팅 </h4>
                                <h4>- 으쌰으쌰 </h4>
                            </div>
                        </div>
                     </div>
                  <!-- Left and right controls -->
                  <a class="left carousel-control" href="#carousel" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left font-green" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="right carousel-control" href="#carousel" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right font-green" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </a>
                </div>
            </section>
        </div>
        
        <!--로그인 후 개인정보 화면 -->
        <% if user_signed_in? %>
        <div class="col-sm-4" style="padding-left:0px; padding-right:0px; height:300px; background-color:transparent; text-align:center">
			<div style="width:90%; margin-left:10%">
				<div style="width: 100%; height:120px; background-color:rgb(255,255,255); border-radius:2px; border: solid 1px rgb(226,228,232); ">
    				
    				<div class="row"  style="height:60px; padding-top:15px; margin:0px; border-bottom: solid 1px rgb(226,228,232);  " >    
                        <div class="col-xs-4" style="padding-right:0px" >
                            <p style="font-weight:600">MY <br> 해시태그</p>
                        </div>
    				    <div class="col-xs-4 " style="margin-bottom:5px">
                            <img src="assets/mango.png" style="width: 32px; padding-bottom: 4px "> <%= @usermango.count  %> 개   
    				    </div>
    				    <div class="col-xs-4" style="padding-left:0px">
                            <img src="assets/melon.png" style="width: 38px; padding-top:1px; padding-right:4px; padding-bottom: 4px "> <%= @usermelon.count  %> 개    
    				    </div>
    				</div>
    				
    				
    				<div style="padding-top:10px; padding-bottom:10px;">
    				    <button class="btn btn-default yellow" style="margin-left:auto; margin-right:auto"><strong>친구 초대하고 망고 받기 </strong></button>
    				</div>
				</div>
				<div style="height: 170px; margin-top:10px; background-color:rgb(255,255,255); border-radius:2px; border: solid 1px rgb(226,228,232); ">
    				<div style="height:37px; border-bottom: solid 1px rgb(226,228,232);">    
    				    <p style="font-weight:27px; font-weight:700; padding-top:12px">실시간 인기 #해시태그</p>
    				</div>
    				   
				    <div class="login-hash-ranking list-inline" style="">
                        
                            <a class="hash-button-small-melon" id="selected"> #다음카카오  </a>
                            <a class="hash-button-small-melon" id="selected"> #빅데이터  </a>
                            <a class="hash-button-small-melon" id="selected"> #금융  </a>
                            <a class="hash-button-small-melon" id="selected"> #매킨지  </a>
                            <a class="hash-button-small-melon" id="selected"> #SK 텔레콤  </a>
                            <a class="hash-button-small-melon" id="selected"> #삼성  </a>
                            <a class="hash-button-small-melon" id="selected"> #네이버  </a>
                            <a class="hash-button-small-melon" id="selected"> #스타트업  </a>
                            <a class="hash-button-small-melon" id="selected"> #공기업 </a>


                        </ul>
				    </div>
				    
				</div>    			
			</div>
        </div>
        
        <!--로그인 후 개인정보 끝 -->
        
        <% else %> 
        
        <!----로그인 전 >-->
        <div class="col-sm-4"  id="login-dp"  >
            <div class="row" style=>
    			<div class="col-xs-12" style="padding-left:40px; padding-right:40px">
    				<div class="social-buttons">
    					<a href="/users/auth/facebook" class="btn btn-fb" style="width: 100%;"><i class="fa fa-facebook"></i> 페이스북으로 로그인하기</a>
    				</div>
                    
    				 <form class="form" role="form" method="post" action="login" accept-charset="UTF-8" id="login-nav">
    					<div class="form-group">
    						 <label class="sr-only" for="exampleInputEmail2">Email address</label>
    						 <input type="email" class="form-control" style="width: 100%;" id="exampleInputEmail2" placeholder="Email 주소" required>
    					</div>
    					<div class="form-group">
    						 <label class="sr-only" for="exampleInputPassword2">Password</label>
    						 <input type="password" class="form-control"  style="width: 100%;" id="exampleInputPassword2" placeholder="비밀번호" required>
                             <div class="help-block text-right"><a href="">비밀번호를 잊으셨나요?</a></div>
    					</div>
    					<div class="form-group">
    						 <button type="submit" class="btn btn-primary btn-block" >Email 로그인 하기</button>
    					</div>
    					<div class="checkbox">
    						 <label>
    						 <input type="checkbox"> 로그인 유지하기
    						 </label>
    					</div>
    				 </form>
    			</div>
    			<div class="bottom text-center">
    				아직 가입하지 않으셨나요? <a href="#"><b>가입하기</b></a>
    			</div>
        	 </div>
        </div>
        
        <% end %>
        
        <!--로그인 시 끝-->
        
        
    </div>
</div>

workspace/app/views/brown/_body_content.erb
<!-- modal call-->




<div id = "whole-contents" class="container-fluid">
        
    
    <!--망고/멜로 선택 탭 -->
    <div id="small-category"  class="btn-group btn-group-justified mango-melon-tab"  role="group" aria-label="...">
      <div class="btn-group" role="group">
        <button type="button" class="btn btn-default btn-mango">망고</button>
      </div>
      <div class="btn-group yellow" role="group">
        <button type="button" class="btn btn-default btn-melon">멜론</button>
      </div>
      <div class="btn-group" role="group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          카테고리
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu dropdown-menu-justified">
          <li><a href="#">인턴</a></li>
          <li><a href="#">공모전</a></li>
          <li><a href="#">대외활동</a></li>
          <li><a href="#">강연</a></li>
          <li><a href="#">동아리</a></li>
        </ul>
      </div>
    </div>

    <!--망고 컨텐츠 제목 -->
    <div id = "contents-head" style="text-align:center">
            <br>
        <div class="yellow contents-headline-block" > 망고 </div> 
        <h4 style="display:inline-block">  정글에서 구해온, 당신을 위한 망고들!</h4>
        <hr style="border: 1px solid rgb(255,204,41); margin-top:2px;">
    </div>
    <div id = "pack-container" class="row">
    <% if !current_user.nil? %>
      <% postlist = Postuserrel.where.not(mango: 0).where("user_id=?",current_user.id).order(mango: :desc).pluck(:post_id) %>
    <% else %>
      <% postlist = Post.pluck(:id) %>
    <% end %>
    <% postlist.each do |x| %>
        <% post = Post.find(x) %>
        <%= render partial: '/brown/inner_content', locals: {post: post} %>
      <% end %>
    </div>
    <!--멜론 컨텐츠 제목 -->
    <div id = "contents-head" style="text-align:center">
            <br>
        <div class="green contents-headline-block" style="color:white" > 멜론 </div> 
        <h4 style="display:inline-block;">  망고 다음으로 소중한 정보들!</h4>
        <hr style="border: 1px solid rgb(65,180,123); margin-top:2px;">
    </div>
    
    <div id = "pack-container" class="row">
    <% if !current_user.nil? %>
      <% postlist = Postuserrel.where.not(melon: 0).where("user_id=? and mango = ?",current_user.id, 0).order(melon: :desc).pluck(:post_id) %>
    <% else %>
      <% postlist = Post.pluck(:id) %>
    <% end %>
    <% postlist.each do |x| %>
        <% post = Post.find(x) %>
        <%= render partial: '/brown/inner_content', locals: {post: post} %>
      <% end %>
    
    </div>
    
</div> <!--컨텐츠 끝-->

workspace/app/views/brown/_footer.erb
<footer style="border-top:solid 2px rgb(65,180,123)">
    <div class="container" >
        <div class="row">
            <div class="col-md-4">
                <span class="copyright">Copyright © 제몽소 2015</span>
            </div>
            <div class="col-md-4">
                <ul class="list-inline social-buttons">
                    <li><a href="#"><i class="fa fa-twitter"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-facebook"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-linkedin"></i></a>
                    </li>
                </ul>
            </div>
            <div class="col-md-4">
                <ul class="list-inline quicklinks">
                    <li><a style="text-decoration: none; color: #222;" href="#">개인정보 보호 관련 규정</a>
                    </li>
                    <li><a style="text-decoration: none; color: #222;" href="#">사용 약관</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>
 

workspace/app/views/brown/_inner_content.erb
<script>
$('#myModal').on('shown.bs.modal', function () {
  $('#myInput').focus()
})
</script>
    <!--망고 팩컨테이너-->
    
        <div class="col-xs-12 col-sm-4" style="margin-top:4px"> 
        <!--컨텐츠 박스 1 -->
        <a data-toggle="modal" data-target="#post<%=post.id%>" style="text-decoration:none!important;">
            <div class="pack-contents"> 
                <div class="pack-top-area">
                    <img id = "pack-img" src= "<%= post.post_image %>" >
                    <h4><%= post.post_company %> </h4>
                    <p><%= post.post_subject %></p> 
                    <ul class="list-inline pack-icon">
                        <li><i class="fa fa-twitter"></i><%= post.post_category %></li>
                        <li><i class="fa fa-calendar"><%= post.post_deadline %></i>
                        </li>
                        <li><i class="fa fa-heart">관심 X 명</i>
                        </li>
                    </ul>
                </div>
               
                <div class="pack-middle-area"> <!--호출된 컨텐츠-->
                    <div class="ellipsis middle-content" >
                        <p> <%= h(post.post_content).gsub( /\n/, '<br />').html_safe %> </p>
                    </div>
                    </a>
                </div>    
                <div class="pack-middle-hash "> <!--호출된 해시태그 --> 
                    <ul class="list-inline">
                        <% if !post.posthashrels.nil? %> 
                        <% i = 1 %>    
                            <% post.posthashrels.each do |hash| %>
                            <% if i%4 == 0 %>
                                <p></p>
                            <% end %>
                           
                            <% if Userhashrel.where("user_id = ? and campushash_id = ?",current_user,hash.campushash_id).take.nil? %>
                                <li><a class="hash-button-small" name="<%=hash.campushash_id%>hash" id="<%=hash.campushash_id%>hash" onclick="pickhash(<%=hash.campushash_id%>, <%=post.id%>)"> #<%= Campushash.find(hash.campushash_id).hash_content %></a></li>
                            <% elsif Userhashrel.where("user_id = ? and campushash_id = ?",current_user,hash.campushash_id).take.pick_type == 0 %>
                                <li><a class="hash-button-small-mango" name="<%=hash.campushash_id%>hash" id="<%=hash.campushash_id%>hash" onclick="pickhash(<%=hash.campushash_id%>, <%=post.id%>)"> #<%= Campushash.find(hash.campushash_id).hash_content %></a></li>
                            <% else %>
                                <li><a class="hash-button-small-melon" name="<%=hash.campushash_id%>hash" id="<%=hash.campushash_id%>hash" onclick="pickhash(<%=hash.campushash_id%>, <%=post.id%>)"> #<%= Campushash.find(hash.campushash_id).hash_content %></a></li>
                            <% end %>
                           
                            <% i = i +1 %>                            
                            <% end %>
                        <% end %>
                    </ul>
                </div>
                
                
                
                <div class="pack-bottom-area ">
                    <a href="#" style="margin-left:10px; margin-right:10px">
                        <i class="fa fa-thumb-tack font-bright-black" style="padding-top:7px; font-weight:500" > 달력에 콕콕  </i> 
                    </a>
                    <a href="#" style="margin-left:10px; margin-right:10px">
                        <i class="fa fa-trash-o font-bright-black" style="padding-top:7px; font-weight:500" > 그만보기  </i> 
                    </a>
                </div>
            </div>
            
        </div>
        
        
        
        

    

workspace/app/views/brown/_login_modal.erb
<div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  
  
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">LOG IN</h4>
      </div>
      <div class="modal-body" style="width:70%; border-right:1px solid #e5e5e5; display:inline-block;">
        
          <!--<form action=/wall/login method=post id=loginform>-->
          <%= form_for(:user, :url => session_path(:user),:html => { :id => "user_login" })  do |f|  %>

              <div class="form-group">
                <!--<label for="recipient-name" class="control-label">ID</label>-->
                 <%= f.label :email, :class => 'control-label' %> <br> 
                <!--<input name=id type="text" class="form-control" id="recipient-name" max="20" required>-->
                <%= f.email_field :email, :class =>'form-control', :id => 'recipient-name', autofocus: true %>
              </div>
              <div class="form-group">
                <!--<label for="message-text" class="control-label">PASSWORD</label>-->
                <%= f.label :password, :class =>'control-form' %><br>
    
                 <!--<input name=password type="password" class="form-control" id="recipient-name" max="20" required>-->
                <%= f.password_field :password, :class =>'form-control', :id => 'recipient-name', autocomplete: "off" %>
              </div>
          <!--</form> -->
          
         
          
          <div class="modal-footer" style="clear:both;">
           
            <%= button_tag(type: 'submit', class: "btn btn-primary", form: "user_login") do %>
               <i class="icon-ok icon-white"></i> Login
            <% end %>
            
            <% end %>
            <!--<button type="submit" form=loginform class="btn btn-primary" style=float:right; >LOG IN</button>-->
            <%if flash[:alert] %>
              <!--<span style="font-size:17px; vertical-align:middle;"><strong><%= flash[:alert] %></strong></span>-->
            <% end %>
            <span style="text-align:left; float:left;"><a data-toggle="modal" data-target="#signin" class="btn btn-primary" >Sign in</a></span>
           
          </div>
         
      </div>
      <div class="modal-body" style="width:29%; height: 60%; position:absolute; display:inline-block;">
        <div style="margin-top:35%;">
          <h5 style="font-weight:600; text-align:center;">페이스북으로<br> 로그인할 수 있습니다 <br><br>
          <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
          <fb:button scope="public_profile,email" onlogin="checkLoginState();">
          </fb:login-button>
          </h5>
        </div>
      </div>
      
    </div>
  </div>
</div>
<script>
if (window.location.hash == "#login") {
     $('#login').modal('show');
}


</script>

<!--login end-->

workspace/app/views/brown/_signup.erb
<div class="modal fade" id="signin" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">SIGN IN</h4>
      </div>
      <div class="modal-body">
      <%= form_for(:user, :url => registration_path(:user),:html => { :id => "user_signup" }) do |f| %>
          <div class="form-group">
            <label for="recipient-name" class="control-label">EMAIL</label>
             <%= f.email_field :email, :class =>'form-control', :id => 'recipient-name', autofocus: true %>
          </div>
          <div class="form-group">
            <label for="message-text" class="control-label">PASSWORD</label>
             <%= f.password_field :password, :class =>'form-control', :id => 'recipient-name', autocomplete: "off" %>
          </div>
           <div class="form-group">
            <label for="message-text" class="control-label">INPUT PASSWORD AGAIN</label>
             <%= f.password_field :password_confirmation, :class =>'form-control', :id => 'recipient-name', autocomplete: "off" %>
          </div>
          <div class="form-group">
          
          </div>
      </form> 
      </div>
      <div class="modal-footer" style="clear:both;">
        <% if flash[:alert] %>
          <%= flash[:alert] %>
        <% end %>
        <%= button_tag(type: 'submit', class: "btn btn-primary", form: "user_signup") do %>
               <i class="icon-ok icon-white"></i> SignUp
        <% end %>
    <% end %>
      </div>
    </div>
  </div>
</div>
<!-- window url call-->
<script>
$(document).ready(function() {

  if(window.location.href.indexOf('#signin') != -1) {
    $('#signin').modal('show');
  }

});
</script>

<!--end-->

workspace/app/views/brown/newpost.erb
<a href=/brown/post_list.erb>게시물 삭제페이지 이동 </a>

<%= form_tag :action => "post_new" do %>
    <%= label_tag(:imageurl, "썸네일 이미지 URL을 입력하세요") %><br>
    <%= text_field_tag(:imageurl) %><br>
    <%= label_tag(:category, "카테고리 입력") %><br>
    <%= text_field_tag(:category) %><br>
    <%= label_tag(:company, "주관하는 회사 입력") %><br>
    <%= text_field_tag(:company) %><br>
    <%= label_tag(:subject, "주제 및 직무")%> <br>
    <%= text_field_tag(:subject) %><br>
    <%= label_tag(:deadline, "기간(만료일)") %><br>
    <%= date_field(:deadline, :date) %><br>
    <%= label_tag(:content, "세부 내용") %><br>
    <%= label_tag(:hash, "해쉬태그를 입력하세요, 구분은 띄어쓰기로! 앞에 #붙이지 마세요!!!") %><br>
    <%= text_field_tag(:hash) %><br>
    <%= text_area_tag(:content, "공모전/인턴 세부 내용 입력", size: "40x10") %> <br>
    <%= submit_tag("Post") %>
<% end %>    

workspace/app/views/brown/post_list.erb
<% @posts.each do |post| %>
<h5><%= post.post_company %> // <%= post.post_subject %> // <%= post.post_deadline %><a href="/brown/post_list/<%=post.id%>"><button type=submit name=post.id value="<%=post.id%>" onclick="return confirm('Are you sure?')">삭제</button></a>  </h5>
<hr>

<% end %>